version: '2'

services:
  calculator:
    build: ./services/calculator

  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'